config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :teams
  resources :games do
    resources :bets
  end
  root 'games#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team_home, :class_name => "Team", :foreign_key => "team_home"
  belongs_to :team_away, :class_name => "Team", :foreign_key => "team_away"
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :home_games, :class_name => "Game", :foreign_key => "team_home"
  has_many :away_games, :class_name => "Game", :foreign_key => "team_away"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, only: %i[ show edit update destroy ]
  before_action :set_game

  # GET /bets or /bets.json
  def index
    @bets = Bet.all
  end

  # GET /bets/1 or /bets/1.json
  def show
  end

  # GET /bets/new
  def new
    @bet = Bet.new
  end

  # GET /bets/1/edit
  def edit
  end

  # POST /bets or /bets.json
  def create
    @bet = Bet.new(bet_params)
    @bet.user = current_user
    @bet.game = @game

    respond_to do |format|
      if @bet.save
        format.html { redirect_to games_url, notice: "Bet was successfully created." }
        format.json { render :show, status: :created, location: @bet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bets/1 or /bets/1.json
  def update
    respond_to do |format|
      if @bet.update(bet_params)
        format.html { redirect_to games_url, notice: "Bet was successfully updated." }
        format.json { render :show, status: :ok, location: @bet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1 or /bets/1.json
  def destroy
    @bet.destroy

    respond_to do |format|
      format.html { redirect_to game_bets_url, notice: "Bet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.find(params[:id])
    end

    def set_game
      @game = Game.find(params[:game_id])
    end

    # Only allow a list of trusted parameters through.
    def bet_params
      params.require(:bet).permit(:team, :score_difference, :game_id)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)
    @game.team_home = Team.find(params[:game][:team_home])
    @game.team_away = Team.find(params[:game][:team_away])
    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    @game.team_home = Team.find(params[:game][:team_home])
    @game.team_away = Team.find(params[:game][:team_away])
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:score_home, :score_away, :date)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to team_url(@team), notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to team_url(@team), notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/bets/_bet.html.erb
<div id="<%= dom_id bet %>">
  <p>
    <strong>Team:</strong>
    <%= bet.team %>
  </p>

  <p>
    <strong>Score difference:</strong>
    <%= bet.score_difference %>
  </p>

  <p>
    <strong>User:</strong>
    <%= bet.user_id %>
  </p>

  <p>
    <strong>Game:</strong>
    <%= bet.game_id %>
  </p>

</div>

app/views/bets/_form.html.erb
<%= form_with(model: bet, url: [game, bet]) do |form| %>
  <% if bet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
        <% bet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :team, style: "display: block" %>
    <%= form.number_field :team %>
  </div>

  <div>
    <%= form.label :score_difference, style: "display: block" %>
    <%= form.number_field :score_difference %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing bet</h1>

<%= render "form", game: @game, bet: @bet %>

<br>

<div>
  <%= link_to "Show this bet", @bet %> |
  <%= link_to "Back to bets", game_bets_path(@game) %>
</div>

app/views/bets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bets</h1>

<div id="bets">
  <% @bets.each do |bet| %>
    <%= render bet %>
    <p>
      <%= link_to "Show this bet", [@game, bet] %>
    </p>
  <% end %>
</div>

<%= link_to "New bet", new_game_bet_path(@game) %>

app/views/bets/new.html.erb
<h1>New bet</h1>

<%= render "form", game: @game, bet: @bet %>

<br>

<div>
  <%= link_to "Back to bets", game_bets_path(@game) %>
</div>

app/views/bets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bet %>

<div>
  <%= link_to "Edit this bet", edit_game_bet_path(@bet) %> |
  <%= link_to "Back to bets", game_bets_path %>

  <%= button_to "Destroy this bet", [@game, @bet], method: :delete %>
</div>

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <table style="table-layout:fixed"; class="table table-striped table-bordered table-hover">
        <td style="width:10%; vertical-align: middle"><strong> <%= form.label :Gospodarz %><%= form.select :team_home, options_for_select(Team.all.map{|s|[s.name, s.id]}) %></strong></td>
        <td style="width:10%; vertical-align: middle"><strong> <%= form.label :Gość %><%= form.select :team_away, options_for_select(Team.all.map{|s|[s.name, s.id]}) %></td>
        <td style="width:10%; vertical-align: middle"><%= form.label :Wynik_gospodarz, style: "display: block" %><%= form.number_field :score_home %></td>
        <td style="width:10%; vertical-align: middle"><%= form.label :Wynik_gość, style: "display: block" %><%= form.number_field :score_away %></td>
        <td style="width:10%; vertical-align: middle"><%= form.label :Data, style: "display: block" %><%= form.datetime_field :date %></td> 
        <td style="width:50%; vertical-align: middle"><button type="submit" class="btn btn-secondary">Zmień</button></td>
  </table>

<% end %>

app/views/games/_game.html.erb
<% bet = Bet.find_or_initialize_by(user: current_user, game: game) %>
<div id="<%= dom_id game %>">
  <table style="table-layout:fixed"; class="table table-striped table-bordered table-hover">
        <td style="width:10%; vertical-align: middle"><strong> <%= game.team_home ? game.team_home.name : "undefined"%></strong></td>
        <td style="width:10%; vertical-align: middle"><strong> <%= game.team_away ? game.team_away.name : "undefined"%></strong></td>
        <td style="width:3%; vertical-align: middle"><%= game.score_home %></td>
        <td style="width:3%; vertical-align: middle"><%= game.score_away %></td>
        <td style="width:3%; vertical-align: middle"><%= game.date %></td> 
        <td style="width:7%"><%= link_to "Pokaż ten mecz", game, class: "btn btn-secondary" %></td>
        <td>

        <% if current_user %>
        <%= form_with(model: bet, url: [game, bet]) do |form| %>
          <%= form.radio_button :team, 0 %> <%= game.team_home ? game.team_home.name : "undefined"%>
          <%= form.radio_button :team, 1 %> <%= game.team_away ? game.team_away.name : "undefined"%>
        <% end %>
      <% end%>

      <script>
  document.addEventListener("DOMContentLoaded", function() {
    const forms = document.querySelectorAll("form");

    forms.forEach((form) => {
      const radioButtons = form.querySelectorAll('input[type="radio"]');
      radioButtons.forEach((radio) => {
        radio.addEventListener("click", function() {
          this.form.submit();

          setTimeout(function() {
            location.reload();
          }, 1000);
        });
      });
    });
  });
</script>
      
        </td>
  </table>
</div>

app/views/games/edit.html.erb
<!doctype html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Typowanie NBA</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
  
  <h1>Edycja meczu</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Pokaż ten mecz", @game, class: "btn btn-secondary" %><br><br>
  <%= link_to "Powtrót do meczy", games_path, class: "btn btn-secondary" %>
</div>

</body>
</html>

app/views/games/index.html.erb
<!doctype html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Typowanie NBA</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>  
    <h1>Mecze</h1>

    <div id="games">
      <% @games.each do |game| %>
        <%= render game %>  
          
      <% end %>
    </div>

  <%= link_to "Nowy mecz", new_game_path, class: "btn btn-secondary" %>
    </body>
</html> 

app/views/games/new.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  
  <h1>Nowy mecz</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Powrót do listy meczy", games_path, class: "btn btn-secondary" %>
</div>

app/views/games/show.html.erb
<!doctype html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Typowanie NBA</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>

  <div id="<%= dom_id @game %>">
    <table style="table-layout:fixed"; class="table table-striped table-bordered table-hover">
        <tr>
          <td style="width:10%; vertical-align: middle"><strong> <%= @game.team_home ? @game.team_home.name : "undefined"%></strong></td>
          <td style="width:10%; vertical-align: middle"><strong> <%= @game.team_away ? @game.team_away.name : "undefined"%></strong></td>
        </tr>
        <tr>
          <td style="width:3%; vertical-align: middle"><%= @game.score_home %></td>
          <td style="width:3%; vertical-align: middle"><%= @game.score_away %></td> 
        </tr>
    </table>
  </div>

<div>
  <%= link_to "Edytuj ten mecz", edit_game_path(@game), class: "btn btn-secondary" %> <br><br>
  <%= link_to "Powrót do listy meczy", games_path, class: "btn btn-secondary" %>
<br><br>
  <%= button_to "Usuń ten mecz", @game, class: "btn btn-danger", method: :delete %>
</div>

  </body>
    </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Typowanie meczy NBA</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
  <body style="background-color:#a8a8a5;">
    <a class="navbar-brand" href="#">Typowanie NBA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
        <%= link_to "Mecze", games_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "Zespoły", teams_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
            <li class="nav-item">
            <%= link_to "Edycja użytkownika", edit_user_registration_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
            <%= link_to "Wyloguj się", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>

            <% else %>

            <li class="nav-item">
            <%= link_to "Zarejestruj się", new_user_registration_path, class: "nav-link" %>
            </li>
            
            <li class="nav-item">
            <%= link_to "Zaloguj się", new_user_session_path, class: "nav-link" %>
            </li>
        <% end %>

      </ul>

    </div>
  </div>
</nav> 

    <%= yield %>
  </body>
</html>